### ISSUE TITLE
sourcemaps?

### ISSUE THREAD

**Issue by contra** [jenius/autoprefixer-stylus#17] opened 2015-01-13 23:55 UTC
seems like this breaks sourcemaps but gulp-autoprefixer does not

**Comment by jenius** [comment] 2015-01-14 02:38
Hmmm... ok let me check this out. It's possible that it might not be returning the right thing out of stylus after the addition of sourcemaps. Do you have a reliable breaking test case by any chance?

**Comment by contra** [comment] 2015-01-14 02:46
@jenius Nothing standalone, but if you use stylus with autoprefixer-stylus and a couple of diff files you will see the stacks are totally pointing to the wrong files and line numbers

**Comment by jenius** [comment] 2015-01-14 02:52
Ok, I'll have this resolved tomorrow :grinning:

**Comment by jenius** [comment] 2015-01-14 19:59
Ok, I see what the issue is, although probably not surprising to anyone. When autoprefixer runs, it modifies the output without also modifying the output sourcemap, causing things to misalign. I'm just going to have it combine the sourcemaps and modify the output as well, that *should* do it.

**Comment by jenius** [comment] 2015-01-14 20:23
Ok so this has been resolved on master but I honestly have absolutely no idea how I'm going to test this. I can verify that the mapping match what's expected, but that doesn't really verify that the maps match up correctly. I took a look into gulp-autoprefixer's tests and it looks like they just match expected mappings.

@contra Is there any chance you could run your manual test against the version that's on master at the moment and verify that it is producing everything correctly before I test for mapping matches?

**Comment by jenius** [comment] 2015-01-14 23:13
Upon further checking, this is definitely not working correctly. It seems like support for multi-stage sourcemaps is pretty weak in general. Autoprefixer maps it back to the  compiled css, but not back to the original stylus code. I looked into how gulp-autoprefixer handles this, and it implements it using the same library as I am using here, so presumably gets the same result -- a sourcemap back to the compiled but not prefixed css, but not all the way back to the stylus.

@contra have you noticed any differences here? It seems like to handle the two-level sourcemap jump, we'll need to use something like [this library](https://github.com/azu/multi-stage-sourcemap), which I'm going to mess around with a bit right now.

**Comment by jenius** [comment] 2015-01-14 23:23
Update: the library in the previous comment did the trick. The code now maps all the way back to the original stylus code. Pretty incredible! Will push this change after a tad bit more testing.

**Comment by jenius** [comment] 2015-01-19 22:30
Released as `0.5.0` last week :grinning:

**Closed by jenius** 2015-01-19 22:30 UTC

**Comment by valdoweb** [comment] 2015-01-26 13:44
Version 0.5.0 seems still breaking to me: [Source map to be applied is missing the "file" property]

**Comment by jenius** [comment] 2015-01-26 15:39
Autoprefixer does not include the `file` property in their returned sourcemaps, which is why it's not returned. It's also not required for the browser to correctly display sourcemaps, and is defined in the sourcemaps v3 spec as an optional property. So the breakage here is actually in whatever library you are using that's throwing an error saying that the `file` property is required, since it's actually optional.

**Comment by valdoweb** [comment] 2015-01-26 18:27
I think you are right, maybe the problem is only using it with gulp-stylus.

**Comment by jenius** [comment] 2015-01-26 19:22
I do want to make sure its useable with gulp-stylus though. Could you post more details on how you are using it? I'll take a look this week.

**Comment by trisys3** [comment] 2015-01-27 04:27
I had the same problem as @valdoweb: using `gulp-stylus` with `autoprefixer-stylus`, the correct sourcemaps are applied, going all the way back to the original `stylus`. I can even do source mapping afterwards, like with `gulp-minify-css`. However, I can't use another sourcemaps library in the same `stylus` task. Both surrounding `stylus` with `sourcemaps.init()/write()` and adding sourcemaps inside `use()` fail with `Potentially unhandled rejection [2] Error: Source map to be applied is missing the "file" property`. This is my breaking task, with source mapping commented out:

    exports.stylus = lazypipe()
        // .pipe(sourcemaps.init, {debug: true})
            .pipe(stylus, {
                linenos: true,
                use: [nib(), prefixer({browsers: ['last 2 versions']})]
                // sourcemap: 'comment'
            })
            .pipe(rename, function(path) {
                path.dirname = path.dirname.replace(/(\/|\\|^)(stylus)(\/|\\|$)/g, "/css/");
            })
        // .pipe(sourcemaps.write);

I would rather have source mapping be (able to be) a separate task, or at least be optional.

**Comment by jenius** [comment] 2015-01-27 05:34
Ok well first issue is that `sourcemap` should be `true` when passed to stylus, not `comment`. If you use that along with gulp-sourcemaps, things will break.

This makes me sad because it seems like I'm straight up trying to fix a gulp error here in an entirely unrelated repo, but alas sometimes that's life. In the gulp-stylus repo there are a bunch of examples that show how to correctly use it with gulp-sourcemaps, including how to make the sourcemaps appear inline. Try it with one of these examples, then post that example back here.

**Comment by trisys3** [comment] 2015-01-27 05:51
Changing `sourceMap` to "true" did not fix the issue.

I apologize if I am making you feel sad, but the issue was certainly with this plugin. Using straight-up `gulp-autoprefixer` worked fine with sourcemaps, so it is something with this plugin. Now, I'm not sure if this is something that needs to be fixed in the first place, but it just seems to go against the `gulp` methodology as you're trying to do 2 things with 1 plugin (autoprefixing and source mapping), and using an external tool breaks the build.

It occurs to me that my earlier source code may have been confusing, so I clarified it. I added all my `require`s and removed `gulp-rename` as it was irrelevant.

**Comment by jenius** [comment] 2015-01-27 06:00
Code above appears to be the same...

**Comment by jenius** [comment] 2015-01-27 06:06
The issue is certainly with gulp, as mentioned earlier, the `file` property is optional as defined in the sourcemaps v3 spec, so throwing an error is incorrect. But that aside, I updated your code in the above example a little bit to make it even more clear. Does this reflect the code you are running now?

**Comment by trisys3** [comment] 2015-01-27 06:23
I apologize again, I suppose I was not reading your earlier comment properly. I certainly feel your pain, about fixing something in the library you're depending on, rather than the library you're supporting. I'm not sure what can be done, without patching `gulp`.

By the way, I am not seeing anything different in the code you changed, but I guess it doesn't matter now that I understand my problem. I am switching to `gulp-autoprefixer` for now, by the way, at least until this can get resolved.

**Comment by contra** [comment] 2015-01-27 07:49
Instead of going back and forth about who is feeling sad why don't we file an issue with gulp-sourcemaps if it is not following the sourcemaps v3 spec? That seems like the productive thing to do

**Comment by contra** [comment] 2015-01-27 07:51
Opened one for you to speed things along ^

**Comment by valdoweb** [comment] 2015-01-27 09:07
This is my task, the error is the same of all other guys. I also confirm that using gulp-autoprefixer after the stylus task (removing autoprefixer-stylus inside) seems to work correctly.

gulp.task('css-dev', function () {
  gulp.src( path.join( originCSS ,'main.styl') )
   .pipe(sourcemaps.init())
  .pipe(stylus({
  	use: [
  		jeet(),
  		rupture(),
  		autoprefixer({
  			browsers : "last 4 version"
  		})
  	]
  }))
   .pipe(sourcemaps.write())
  .pipe( rename( fileDestCSS ) )
  .pipe( gulp.dest( basePath ) );
});

autoprefixer-stylus 0.5.0, gulp-stylus 2.0.0 , gulp 3.8.10

**Comment by trisys3** [comment] 2015-01-27 13:00
That's an amazing idea. I will go look at that other issue, though I may not be able to do much as I unexpectedly have work today again.

**Comment by jenius** [comment] 2015-01-27 15:44
Thanks @contra. It doesn't seem like I'm getting anywhere in obtaining more info on what code is being run to produce the problem here despite many comments, so I'm just going to investigate this myself when I have a few moments to do so. Will post back here with results when it's closed out. For now I'd just use gulp-autoprefixer -- this seems like a more natural fit with gulp pipelines anyway to me.

**Comment by jenius** [comment] 2015-01-27 15:45
Also guys when you are posting code, please make sure that it's in a correctly highlighted code block and indented. This really helps me to be able to read it.

**Comment by trisys3** [comment] 2015-01-27 15:54
I was looking at `sautoprefixer-stylus` because I thought it would be good to have the prefixes applied in the stylus phase but yes it always felt a little off to couple the 2 together.

**Comment by jenius** [comment] 2015-01-27 15:59
Sure, I can see it that way for gulp definitely. That being said I work on a few pipeline tools that are not grunt that work perfectly fine with this plugin.
